import numpy as np

def tanh(x):
    return np.tanh(x)

# Initialize a cell state
cell_state = np.array([0.5, -0.1, 0.1])

# Define forget and input gates (manually for this example)
# Forget gate: Suppose we want to forget the second element and remember the first and third
forget_gate = np.array([1, 0, 1])

# Input gate: We have new information we want to add to the cell state (only in the second element for simplicity)
input_gate = np.array([0, 1, 0])

# New candidate values to be added to the cell state (generated by the cell gate in a real LSTM)
candidate_values = np.array([0.0, 0.2, 0.0])

# Update the cell state
first_half = forget_gate * cell_state
second_half = input_gate * candidate_values

updated_cell_state = first_half + second_half

print("Original cell state:", cell_state)
print("Updated cell state:", updated_cell_state)
